version: "3.9"

services:
  rahtek-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rahtek-backend:latest
    container_name: rahtek-backend-container
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rahtek
      PORT: 4040
    depends_on:
      - postgres
    restart: unless-stopped
    command: ["dumb-init", "node", "dist/index.js"]

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: rahtek-db-container
    volumes:
      - db-data:/var/lib/rahtek-db-volume
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rahtek
    env_file:
      - ./.env
    restart: always
volumes:
  db-data:
